name: Docker Image CI

# on:
#   release:
#     types:
#      - "released"

on:
  push:
    branches:
      - "main"

jobs:

  build-publish:
    name: build and push docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: push a new tag
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: jackkweyunga/github-flask-docker
        addLatest: true
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
  deploy:
    needs: [build-publish]
    name: deploy to server
    runs-on: ubuntu-latest
    steps:
    - name: checkout to the branch
      uses: actions/checkout@v2
    - name: copy required files to server
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: ./flask-git-docker/
        remote_path: /home/${{ secrets.SSH_USERNAME }}/flask-git-docker/
        remote_host: ${{ secrets.SSH_HOST }}
        remote_user: ${{ secrets.SSH_USERNAME }}
        remote_key: ${{ secrets.SSH_KEY }}
    - name: ssh to copy files and deploy project
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ./flask-git-docker
          chmod +x run.sh
          ./run.sh

#     env:
#       SSH_KEY: ${{ secrets.SSH_KEY }}
#       SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
#       SSH_HOST: ${{ secrets.SSH_HOST }}
          
        
